java_library(
  name = 'timbuctoo-test-services',
  srcs = glob(['src/main/java/**/*.java']),
  deps = [
    "//third-party/guava:guava",
    "//third-party/hamcrest:hamcrest-all",
  ],
  exported_deps = [
  ],
  visibility = [
    "PUBLIC"
  ]
)