java_library(
  name = 'ContractDiff',
  srcs = glob(['src/main/java/**/*.java']),
  deps = [
    "//third-party/core:jackson-core",
    "//third-party/core:jackson-databind",
    "//third-party/guava:guava"
  ],
  exported_deps = [
  ],
  visibility = [
    "PUBLIC"
  ]
)