java_library(
  name = 'security-client-agnostic',
  srcs = glob(['src/main/java/**/*.java']),
  deps = [
    "//third-party/guava:guava",
    "//third-party/huygens:security-core",
  ],
  exported_deps = [
  ],
  visibility = [
    "PUBLIC"
  ]
)